#******************************************************************
#
# Copyright 2015 Samsung Electronics All Rights Reserved.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

##
# linux sample app  build script (Sample Client & Sample Server)
##
Import('env')

# Add third party libraries
lib_env = env.Clone()
SConscript(env.get('SRC_DIR') + '/service/third_party_libs.scons', 'lib_env')

rich_server_program_env = lib_env.Clone()

######################################################################
# Build flags
######################################################################
rich_server_program_env.AppendUnique(CPPPATH = ['../../../extlibs/cjson'])
rich_server_program_env.AppendUnique(CPPPATH = ['../../../resource/csdk/connectivity/api'])
rich_server_program_env.AppendUnique(CXXFLAGS = ['-O2', '-g', '-Wall', '-fmessage-length=0', '-std=c++0x'])
rich_server_program_env.AppendUnique(CPPPATH = ['../include'])
rich_server_program_env.AppendUnique(CPPPATH = ['../../resource-encapsulation/include'])
rich_server_program_env.AppendUnique(CPPPATH = ['../../resource-encapsulation/src/common/primitiveResource/include'])
rich_server_program_env.AppendUnique(CPPPATH = ['../../resource-encapsulation/src/common/expiryTimer/include'])
rich_server_program_env.AppendUnique(CPPPATH = ['../../resource-hosting/src'])

rich_server_program_env.AppendUnique(LIBS = [
    'resource_hosting',
    'rcs_client',
    'rcs_server',
    'rich_server',
    'rcs_common',
    'oc',
    'octbstack',
    'oc_logger',
    'connectivity_abstraction',
    'coap',
    'pthread'
    ])
rich_server_program_env.AppendUnique(CPPPATH = ['../include'])

if env.get('SECURED') == '1':
    rich_server_program_env.AppendUnique(LIBS = ['tinydtls'])

if 'rt' in rich_server_program_env.get('LIBS'):
    rich_server_program_env.Append(LIBS = ['rt'])

######################################################################
# ##### Client #####
######################################################################

richServerMain = rich_server_program_env.Program('rich_server_main', 'main.cpp')

rich_server_program_env.InstallTarget(richServerMain, 'rich_server_main')

